### ISSUE TITLE
Filtering documents by relationship

### ISSUE THREAD

**Issue by tyteen4a03** [arshad/next-mdx#6]
I have two types of nodes: Post and Snippet. I would like a Post to be composed of multiple snippets (which Snippet it belongs to is defined in the Snipper's front matter), while retaining the ability to refer to a Snippet on its own.

Is it possible to call `getAll*Nodes('snippet')` from the Post document and only have it return the Snippets that belong to the post?

**Comment by arshad** [comment]
Can you give an example of a `post` and `snippet` frontMatter so we can determine the relationship?

Thank you

**Comment by tyteen4a03** [comment]
post.md:
```
---
title: Post
---
```

snippet.md:
```
---
title: Snippet
belongsToPost: post
---
```

**Comment by arshad** [comment]
OK. Let me see. I'll try to put together a quick example.

**Comment by arshad** [comment]
OK I created an example here:

Demo: https://next-mdx-post-snippet.vercel.app
Repo: https://github.com/arshad/next-mdx-post-snippet

Here are some key parts:

## Define your MDX types

https://github.com/arshad/next-mdx-post-snippet/blob/25aed7eefcb2616fd7da311189eff2071fa6fa20/next-mdx.json#L1

```json
{
  "post": {
    "contentPath": "content/posts",
    "basePath": "/blog"
  },
  "snippet": {
    "contentPath": "content/snippets"
  }
}
```

## Set the post in the snippet

```md
---
title: Hello World
post: <------- This must match the key we used above in next-mdx.json
  - first-post <-----------------
---

```jsx
export function HelloWorld() {
  return <p>Hello World</p>
}
```

## Get the snippets for a post

```js
export async function getStaticProps(context) {
  const post = await getMdxNode("post", context)

  if (!post) {
    return {
      notFound: true,
    }
  }

  const snippets = await getAllMdxNodes("snippet")

  return {
    props: {
      post,
      snippets: snippets.filter((snippet) =>
        snippet.relationships.post.some(({ slug }) => slug === post.slug)
      ),
    },
  }
}
```

https://github.com/arshad/next-mdx-post-snippet/blob/25aed7eefcb2616fd7da311189eff2071fa6fa20/pages/blog/%5B...slug%5D.tsx#L46

Hope this helps

**Comment by tyteen4a03** [comment]
OK so as I suspected I would need to do the filtering myself. Thanks either way :)
